### ISSUE TITLE
Exclude OSX .DS_Store files by default

### ISSUE THREAD

**Issue by robertoschwald** [beckje01/grails-code-coverage#14]
Please exclude .DS_Store OSX specific files by default. The're generated by the OSX Finder when accessing project folders:

```
| Compiling 103 source files...
| Instrumenting classes for coverage.
Unable to obtain resource from /example-project/grails-app/.DS_Store: java.util.zip.ZipException: error in opening zip file
  [taskdef] Unable to obtain resource from /example-project/grails-app/.DS_Store: 
  [taskdef] java.util.zip.ZipException: error in opening zip file
  [taskdef]     at java.util.zip.ZipFile.open(Native Method)
  [taskdef]     at java.util.zip.ZipFile.<init>(ZipFile.java:215)
  [taskdef]     at java.util.zip.ZipFile.<init>(ZipFile.java:145)
  [taskdef]     at java.util.jar.JarFile.<init>(JarFile.java:153)
  [taskdef]     at java.util.jar.JarFile.<init>(JarFile.java:117)
  [taskdef]     at org.apache.tools.ant.AntClassLoader.getResourceURL(AntClassLoader.java:1002)
  [taskdef]     at org.apache.tools.ant.AntClassLoader$ResourceEnumeration.findNextResource(AntClassLoader.java:145)
  [taskdef]     at org.apache.tools.ant.AntClassLoader$ResourceEnumeration.<init>(AntClassLoader.java:109)
  [taskdef]     at org.apache.tools.ant.AntClassLoader.findResources(AntClassLoader.java:949)
  [taskdef]     at org.apache.tools.ant.AntClassLoader.getNamedResources(AntClassLoader.java:918)
  [taskdef]     at org.apache.tools.ant.loader.AntClassLoader5.getResources(AntClassLoader5.java:56)
  [taskdef]     at org.apache.tools.ant.taskdefs.Definer.resourceToURLs(Definer.java:375)
  [taskdef]     at org.apache.tools.ant.taskdefs.Definer.execute(Definer.java:267)
  [taskdef]     at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
  [taskdef]     at sun.reflect.GeneratedMethodAccessor157.invoke(Unknown Source)
  [taskdef]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  [taskdef]     at java.lang.reflect.Method.invoke(Method.java:606)
  [taskdef]     at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
  [taskdef]     at groovy.util.AntBuilder.performTask(AntBuilder.java:260)
  [taskdef]     at groovy.util.AntBuilder.nodeCompleted(AntBuilder.java:220)
  [taskdef]     at groovy.util.BuilderSupport.doInvokeMethod(BuilderSupport.java:147)
  [taskdef]     at groovy.util.AntBuilder.doInvokeMethod(AntBuilder.java:170)
  [taskdef]     at groovy.util.BuilderSupport.invokeMethod(BuilderSupport.java:64)
  [taskdef]     at org.codehaus.gant.GantBuilder.invokeMethod(GantBuilder.java:99)
  [taskdef]     at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:45)
  [taskdef]     at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)
  [taskdef]     at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
  [taskdef]     at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
  [taskdef]     at _Events.defineCoberturaPathAndTasks(_Events.groovy:101)
```

**Comment by beckje01** [comment]
I can reproduce this but there doesn't seem to be a clear way to prevent this from happening it is currently using the ant.taskdef and a resource the class path being used is grails.test.classpath This warning shouldn't cause any real issue doing the work.
