### ISSUE TITLE
grails test-app coverage throws java.lang.SecurityException: class "com.ibm.icu.util.TimeZone"'s signer information does not match signer information of other classes in the same package

### ISSUE THREAD

**Issue by asuraphel** [beckje01/grails-code-coverage#36]
I get the following: 

General error during class generation: class "com.ibm.icu.util.TimeZone"'s signer information does not match signer information of other classes in the same package

java.lang.SecurityException: class "com.ibm.icu.util.TimeZone"'s signer information does not match signer information of other classes in the same package
        at java.lang.ClassLoader.checkCerts(ClassLoader.java:952)
        at java.lang.ClassLoader.preDefineClass(ClassLoader.java:666)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:794)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at org.codehaus.groovy.tools.RootLoader.oldFindClass(RootLoader.java:171)
        at org.codehaus.groovy.tools.RootLoader.loadClass(RootLoader.java:143)
        at org.codehaus.groovy.grails.cli.support.GrailsRootLoader.loadClass(GrailsRootLoader.java:51)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2531)
        at java.lang.Class.getDeclaredMethods(Class.java:1855)
        at org.codehaus.groovy.vmplugin.v5.Java5.configureClassNode(Java5.java:354)
        at org.codehaus.groovy.ast.ClassNode.lazyClassInit(ClassNode.java:258)
        at org.codehaus.groovy.ast.ClassNode.getInterfaces(ClassNode.java:353)
        at org.codehaus.groovy.ast.ClassNode.declaresInterface(ClassNode.java:945)
        at org.codehaus.groovy.ast.ClassNode.declaresInterface(ClassNode.java:950)
        at org.codehaus.groovy.ast.ClassNode.implementsInterface(ClassNode.java:925)
        at org.codehaus.groovy.ast.ClassNode.isDerivedFromGroovyObject(ClassNode.java:915)
        at org.codehaus.groovy.classgen.AsmClassGenerator.isGroovyObject(AsmClassGenerator.java:937)
        at org.codehaus.groovy.classgen.AsmClassGenerator.visitPropertyExpression(AsmClassGenerator.java:888)
        at org.codehaus.groovy.ast.expr.PropertyExpression.visit(PropertyExpression.java:55)
        at org.codehaus.groovy.classgen.asm.BinaryExpressionHelper.evaluateEqual(BinaryExpressionHelper.java:369)
        at org.codehaus.groovy.classgen.asm.BinaryExpressionHelper.eval(BinaryExpressionHelper.java:78)
        at org.codehaus.groovy.classgen.AsmClassGenerator.visitBinaryExpression(AsmClassGenerator.java:565)
        at org.codehaus.groovy.ast.expr.BinaryExpression.visit(BinaryExpression.java:49)
        at org.codehaus.groovy.classgen.asm.StatementWriter.writeExpressionStatement(StatementWriter.java:604)
        at org.codehaus.groovy.classgen.asm.OptimizingStatementWriter.writeExpressionStatement(OptimizingStatementWriter.java:354)
        at org.codehaus.groovy.classgen.AsmClassGenerator.visitExpressionStatement(AsmClassGenerator.java:547)
        at org.codehaus.groovy.ast.stmt.ExpressionStatement.visit(ExpressionStatement.java:40)
        at org.codehaus.groovy.classgen.asm.StatementWriter.writeBlockStatement(StatementWriter.java:81)

...

**Comment by robertoschwald** [comment]
Seems you have duplicate dependencies on your classpath. Check your classpath using dependency-report for the icu package.

**Comment by ahassen** [comment]
I'm having similar problems. And there are no duplicate dependencies on my classpath. @robertoschwald

**Comment by asuraphel** [comment]
```
test(":code-coverage:2.0.3-3") { 
        excludes 'icu4j'
}
```

solved it as the icu4j jar was used in one of our other plugins. 

CC: @ahassen
